package com.example.mlbackend.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

/**
 * Represents the combined output of all ML models in the predictive maintenance pipeline.
 * 
 * This model maps to the predictions table in Supabase and contains all the values
 * generated by the different ML models:
 * 1. Anomaly detection (boolean from autoencoder)
 * 2. Failure probability (float from random forest classifier)
 * 3. Health index (float from random forest regressor)
 * 4. Remaining useful life (float from LSTM)
 * 5. Part at risk prediction (string from DL4J classifier)
 * 
 * Each prediction applies to a specific device at a specific point in time.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class PredictionResult {
    private Long id;
    private String deviceId;
    private LocalDateTime timestamp;
    private boolean isAnomaly;
    private double failureProbability;
    private double healthIndex;
    private double remainingUsefulLife;
    private String partAtRisk;
    private String condition;
} 